### ISSUE TITLE
NFO.Editor.v9.1.9打不开出现报错

### ISSUE THREAD

**Issue by mangguo144** [cgkings/NFO.Editor#7]
NFO.Editor.v9.1.9打不开出现报错

![Quicker_20241118_001647](https://github.com/user-attachments/assets/13d2323a-bfcf-4fd6-a470-a1229d609ee6)

求大佬教教怎么处理。

**Comment by cgkings** [comment]
更新v9.2.0，是因为没有把winshell模块写进requirements.txt
