### ISSUE TITLE
The image display feature is not working

### ISSUE THREAD

**Issue by epubc** [cgkings/NFO.Editor#8]
The image display feature is not working. It only shows the first image of the Video, the next Videos will not be displayed.
![2024-12-04_073433](https://github.com/user-attachments/assets/9d7b2ed5-d313-4708-89b3-87253b38f127)
![2024-12-04_073453](https://github.com/user-attachments/assets/2be2028c-577a-4ebe-aac8-ed2b5a559031)

**Comment by cgkings** [comment]
update to v9.3.3
